language: java
sudo: required
services:
  - docker
jdk:
  - oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE=microshop/orders
    - IMAGE_VERSION=$IMAGE:$COMMIT

before_script:
  - docker build -t $IMAGE:$COMMIT .
  - docker tag $IMAGE:$COMMIT $IMAGE:latest
  - docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER

script:
  - docker version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $IMAGE

  # Install kubernetes and set config
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -o config https://$GITHUB_ACCESS_TOKEN@raw.githubusercontent.com/micro-shop/config/master/kubeconfig

  - mkdir ${HOME}/.kube
  - cp config ${HOME}/.kube/config

  # Fill out missing params in kubectl config file
  - sed -i -e 's|KUBE_CA_CERT|'"${KUBE_CA_CERT}"'|g' config
  - sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' config
  - sed -i -e 's|KUBE_TRAVIS_CERT|'"${KUBE_TRAVIS_CERT}"'|g' config
  - sed -i -e 's|KUBE_TRAVIS_KEY|'"${KUBE_TRAVIS_KEY}"'|g' config
  - sed -i -e 's|KUBE_USERNAME|'"${KUBE_USERNAME}"'|g' config
  - sed -i -e 's|KUBE_CONTEXT_NAME|'"${KUBE_CONTEXT_NAME}"'|g' config
  - sed -i -e 's|KUBE_CLUSTER_NAME|'"${KUBE_CLUSTER_NAME}"'|g' config
  - kubectl apply -f .\deployment\deployment.yml
  #- kubectl set image deployment/<deplyoment name> <deplyoment name>=<your docker registry>/<image name>:<version>