language: java
sudo: required
services:
  - docker
jdk:
  - oraclejdk8
install: true

env:
  - GROUP=micro-shop COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=orders;

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
          push "$REPO:$TAG";
  - export NAME=$GROUP/$REPO
  - docker build -t $NAME:$COMMIT
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME